baseURL = "https://darreng1234.github.io/"
languageCode = "en-us"
theme = "anubis2"
title = "Darren Blog"

[author]
name = "Darren Gomez"

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[[menu.main]]
identifier = "home"
name = "Home"
url = "/personal-blog/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/personal-blog/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/personal-blog/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/personal-blog/posts/"
weight = 4